### ISSUE TITLE
What is the font ? 

### ISSUE THREAD

**Issue by LucasVanco** [xaverh/theme-ysgrifennwr#1]
Hello @xaverh ,

Can you share with me the font you used in your screenshot please, it looks very neat.

Thanks in advance.

**Comment by xaverh** [comment]
Hello @TresorDeKelloggS,

this is [Input](http://input.fontbureau.com/) (more precisely Input Mono Condensed). I use it with these settings: http://input.fontbureau.com/download/?customize&fontSelection=fourStyleFamily&regular=InputMonoCondensed-Regular&italic=InputMonoCondensed-Italic&bold=InputSansCondensed-Bold&boldItalic=InputMonoCondensed-BoldItalic&a=0&g=ss&i=topserif&l=topserif&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.2&email=

If you are using Archlinux (and statistically you are not :slightly_smiling_face:) you can use this PKGBUILD: https://github.com/xaverh/ttf-input

**Comment by LucasVanco** [comment]
Thanks mate !
